[env:aura]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps =
    ArduinoStubs=symlink://lib/arduino_stubs
    Lora=symlink://lib/lora
    Net=symlink://lib/net
build_src_filter =
    +<*.cpp>
build_flags = -D CIROH_BOARD -D CIROH_GATEWAY -D CIROH_TDMA -Wall -Wextra
extra_scripts =
    pre:common/macro_defines.py
    post:common/gen_compile_commands.py
